import { RefreshToken } from './refresh-token.entity';

export const REFRESH_TOKEN_REPOSITORY = Symbol('REFRESH_TOKEN_REPOSITORY');

export interface IRefreshTokenRepository {
  /** `id` is generated by the caller (AuthService) BEFORE signing, so it can be embedded as the JWT's `jti` and match this row. */
  create(id: string, userId: string, tokenHash: string, expiresAt: Date): Promise<RefreshToken>;
  /** Finds an active (not revoked, not expired) refresh token row by its id (the JWT's `jti`). */
  findActiveById(id: string): Promise<RefreshToken | null>;
  revoke(id: string): Promise<void>;
  revokeAllForUser(userId: string): Promise<void>;
}
