/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Numeric = ColumnType<string, number | string, number | string>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface ActivityHistory {
  action: string;
  created_at: Generated<Timestamp>;
  description: string;
  entity_id: string;
  entity_type: string;
  id: Generated<string>;
  user_id: string | null;
}

export interface ApprovalWorkflows {
  approver_role_id: string;
  document_type: string;
  id: Generated<string>;
  is_active: Generated<boolean>;
  min_amount: Numeric | null;
}

export interface AuditLogs {
  action: string;
  changed_at: Generated<Timestamp>;
  changed_by: string | null;
  id: Generated<string>;
  new_data: Json | null;
  old_data: Json | null;
  record_id: string;
  table_name: string;
}

export interface BlockedStockEntries {
  batch_id: string | null;
  blocked_at: Generated<Timestamp>;
  blocked_by: string | null;
  id: Generated<string>;
  location_id: string | null;
  product_id: string;
  quantity: Numeric;
  rack_id: string | null;
  reason: string;
  released_at: Timestamp | null;
  released_by: string | null;
  status: Generated<string>;
  warehouse_id: string;
}

export interface Branches {
  address_line1: string | null;
  address_line2: string | null;
  city: string | null;
  code: string;
  country: string | null;
  created_at: Generated<Timestamp>;
  email: string | null;
  id: Generated<string>;
  is_active: Generated<boolean>;
  is_head_office: Generated<boolean>;
  name: string;
  phone: string | null;
  pincode: string | null;
  state: string | null;
  updated_at: Generated<Timestamp>;
}

export interface Brands {
  code: string;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  is_active: Generated<boolean>;
  logo_url: string | null;
  name: string;
  updated_at: Generated<Timestamp>;
}

export interface Categories {
  code: string;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  is_active: Generated<boolean>;
  name: string;
  updated_at: Generated<Timestamp>;
}

export interface CustomerPaymentAllocations {
  allocated_amount: Numeric;
  id: Generated<string>;
  payment_id: string;
  sales_invoice_id: string;
}

export interface CustomerPayments {
  amount: Numeric;
  created_at: Generated<Timestamp>;
  created_by: string | null;
  customer_id: string;
  id: Generated<string>;
  payment_date: Generated<Timestamp>;
  payment_mode: string;
  payment_number: string;
  reference_number: string | null;
  remarks: string | null;
}

export interface Customers {
  address_line1: string | null;
  address_line2: string | null;
  blocked_reason: string | null;
  city: string | null;
  code: string;
  contact_person: string | null;
  country: string | null;
  created_at: Generated<Timestamp>;
  credit_limit: Generated<Numeric>;
  credit_period_days: Generated<number>;
  email: string | null;
  gstin: string | null;
  id: Generated<string>;
  is_active: Generated<boolean>;
  is_blocked: Generated<boolean>;
  name: string;
  opening_balance: Generated<Numeric>;
  pan: string | null;
  phone: string | null;
  pincode: string | null;
  state: string | null;
  updated_at: Generated<Timestamp>;
}

export interface DamagedStock {
  approved_at: Timestamp | null;
  approved_by: string | null;
  created_at: Generated<Timestamp>;
  created_by: string | null;
  damage_date: Generated<Timestamp>;
  damage_number: string;
  id: Generated<string>;
  reason: string | null;
  status: Generated<string>;
  updated_at: Generated<Timestamp>;
  warehouse_id: string;
}

export interface DamagedStockLines {
  batch_id: string | null;
  damage_id: string;
  id: Generated<string>;
  location_id: string | null;
  product_id: string;
  quantity: Numeric;
  rack_id: string | null;
  remarks: string | null;
}

export interface DeliveryChallanLines {
  batch_id: string | null;
  dc_id: string;
  id: Generated<string>;
  product_id: string;
  product_unit_id: string;
  quantity: Numeric;
  remarks: string | null;
  so_line_id: string | null;
}

export interface DeliveryChallans {
  created_at: Generated<Timestamp>;
  created_by: string | null;
  customer_id: string;
  dc_date: Generated<Timestamp>;
  dc_number: string;
  id: Generated<string>;
  remarks: string | null;
  so_id: string | null;
  status: Generated<string>;
  transporter_id: string | null;
  updated_at: Generated<Timestamp>;
  warehouse_id: string;
}

export interface DocumentNumberSequences {
  document_type: string;
  financial_year_id: string;
  id: Generated<string>;
  last_number: Generated<number>;
  prefix: string;
}

export interface Employees {
  code: string;
  created_at: Generated<Timestamp>;
  department: string | null;
  designation: string | null;
  email: string | null;
  id: Generated<string>;
  is_active: Generated<boolean>;
  joining_date: Timestamp | null;
  name: string;
  phone: string | null;
  updated_at: Generated<Timestamp>;
  user_id: string | null;
}

export interface FinancialYears {
  created_at: Generated<Timestamp>;
  end_date: Timestamp;
  id: Generated<string>;
  is_closed: Generated<boolean>;
  is_current: Generated<boolean>;
  name: string;
  start_date: Timestamp;
  updated_at: Generated<Timestamp>;
}

export interface GoodsReceivedNotes {
  created_at: Generated<Timestamp>;
  created_by: string | null;
  grn_date: Generated<Timestamp>;
  grn_number: string;
  id: Generated<string>;
  po_id: string | null;
  remarks: string | null;
  status: Generated<string>;
  supplier_id: string;
  transporter_id: string | null;
  updated_at: Generated<Timestamp>;
  warehouse_id: string;
}

export interface GrnLines {
  batch_id: string | null;
  grn_id: string;
  id: Generated<string>;
  po_line_id: string | null;
  product_id: string;
  product_unit_id: string;
  quantity: Numeric;
  rate: Numeric;
  remarks: string | null;
}

export interface GstRates {
  cgst_rate: Numeric;
  id: Generated<string>;
  igst_rate: Numeric;
  is_active: Generated<boolean>;
  name: string;
  sgst_rate: Numeric;
  total_rate: Numeric;
}

export interface HsnCodes {
  code: string;
  default_gst_id: string | null;
  description: string | null;
  id: Generated<string>;
  is_active: Generated<boolean>;
}

export interface Locations {
  code: string;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  is_active: Generated<boolean>;
  name: string;
  rack_id: string;
  updated_at: Generated<Timestamp>;
}

export interface Notifications {
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  is_read: Generated<boolean>;
  message: string;
  reference_id: string | null;
  reference_type: string | null;
  title: string;
  type: string;
  user_id: string | null;
}

export interface OtpCodes {
  code_hash: string;
  consumed_at: Timestamp | null;
  created_at: Generated<Timestamp>;
  expires_at: Timestamp;
  id: Generated<string>;
  purpose: string;
  user_id: string;
}

export interface Permissions {
  action: string;
  code: string;
  id: Generated<string>;
  module: string;
}

export interface PhysicalVerificationLines {
  batch_id: string | null;
  counted_quantity: Numeric;
  difference: Generated<Numeric | null>;
  id: Generated<string>;
  location_id: string | null;
  product_id: string;
  rack_id: string | null;
  remarks: string | null;
  system_quantity: Numeric;
  verification_id: string;
}

export interface PhysicalVerifications {
  completed_at: Timestamp | null;
  created_at: Generated<Timestamp>;
  created_by: string | null;
  id: Generated<string>;
  status: Generated<string>;
  updated_at: Generated<Timestamp>;
  verification_date: Generated<Timestamp>;
  verification_number: string;
  warehouse_id: string;
}

export interface ProductBarcodes {
  barcode: string;
  barcode_type: Generated<string>;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  is_primary: Generated<boolean>;
  product_id: string;
  product_unit_id: string | null;
}

export interface ProductBatches {
  batch_number: string;
  created_at: Generated<Timestamp>;
  expiry_date: Timestamp | null;
  id: Generated<string>;
  lot_number: string | null;
  manufacturing_date: Timestamp | null;
  product_id: string;
}

export interface ProductImages {
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  image_url: string;
  is_primary: Generated<boolean>;
  product_id: string;
  sort_order: Generated<number>;
}

export interface ProductPriceHistory {
  changed_at: Generated<Timestamp>;
  changed_by: string | null;
  id: Generated<string>;
  new_price: Numeric;
  old_price: Numeric | null;
  price_type: string;
  product_id: string;
}

export interface Products {
  barcode: string | null;
  base_unit_id: string;
  brand_id: string | null;
  category_id: string;
  created_at: Generated<Timestamp>;
  dimension_height: Numeric | null;
  dimension_length: Numeric | null;
  dimension_unit: string | null;
  dimension_width: Numeric | null;
  gst_id: string | null;
  has_batch_tracking: Generated<boolean>;
  has_expiry_tracking: Generated<boolean>;
  hsn_id: string | null;
  id: Generated<string>;
  is_active: Generated<boolean>;
  maximum_stock: Numeric | null;
  minimum_stock: Generated<Numeric>;
  mrp: Numeric | null;
  name: string;
  opening_stock: Generated<Numeric>;
  pieces_per_bag: number | null;
  pieces_per_box: number | null;
  purchase_price: Generated<Numeric>;
  qr_code: string | null;
  remarks: string | null;
  reorder_level: Generated<Numeric>;
  selling_price: Generated<Numeric>;
  sku: string;
  sub_category_id: string | null;
  updated_at: Generated<Timestamp>;
  weight: Numeric | null;
  weight_unit: string | null;
}

export interface ProductUnits {
  barcode: string | null;
  conversion_factor: Numeric;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  is_base_unit: Generated<boolean>;
  product_id: string;
  purchase_price: Numeric | null;
  selling_price: Numeric | null;
  unit_id: string;
}

export interface PurchaseInvoiceLines {
  batch_id: string | null;
  discount_percent: Generated<Numeric>;
  gst_id: string | null;
  id: Generated<string>;
  invoice_id: string;
  line_total: Generated<Numeric>;
  product_id: string;
  product_unit_id: string;
  quantity: Numeric;
  rate: Numeric;
  tax_amount: Generated<Numeric>;
}

export interface PurchaseInvoices {
  approved_at: Timestamp | null;
  approved_by: string | null;
  created_at: Generated<Timestamp>;
  created_by: string | null;
  discount_amount: Generated<Numeric>;
  due_date: Timestamp | null;
  financial_year_id: string;
  grn_id: string | null;
  id: Generated<string>;
  invoice_date: Generated<Timestamp>;
  invoice_number: string;
  paid_amount: Generated<Numeric>;
  po_id: string | null;
  status: Generated<string>;
  subtotal: Generated<Numeric>;
  supplier_id: string;
  supplier_invoice_number: string | null;
  tax_amount: Generated<Numeric>;
  total_amount: Generated<Numeric>;
  updated_at: Generated<Timestamp>;
}

export interface PurchaseOrderLines {
  discount_percent: Generated<Numeric>;
  gst_id: string | null;
  id: Generated<string>;
  line_total: Generated<Numeric>;
  po_id: string;
  product_id: string;
  product_unit_id: string;
  quantity: Numeric;
  rate: Numeric;
  received_quantity: Generated<Numeric>;
}

export interface PurchaseOrders {
  approved_at: Timestamp | null;
  approved_by: string | null;
  created_at: Generated<Timestamp>;
  created_by: string | null;
  expected_delivery_date: Timestamp | null;
  financial_year_id: string;
  id: Generated<string>;
  po_date: Generated<Timestamp>;
  po_number: string;
  remarks: string | null;
  status: Generated<string>;
  supplier_id: string;
  total_amount: Generated<Numeric>;
  updated_at: Generated<Timestamp>;
  warehouse_id: string;
}

export interface PurchaseReturnLines {
  batch_id: string | null;
  id: Generated<string>;
  line_total: Generated<Numeric>;
  product_id: string;
  quantity: Numeric;
  rate: Numeric;
  return_id: string;
}

export interface PurchaseReturns {
  approved_at: Timestamp | null;
  approved_by: string | null;
  created_at: Generated<Timestamp>;
  created_by: string | null;
  id: Generated<string>;
  purchase_invoice_id: string | null;
  reason: string | null;
  return_date: Generated<Timestamp>;
  return_number: string;
  status: Generated<string>;
  supplier_id: string;
  total_amount: Generated<Numeric>;
  updated_at: Generated<Timestamp>;
  warehouse_id: string;
}

export interface QuotationLines {
  discount_percent: Generated<Numeric>;
  gst_id: string | null;
  id: Generated<string>;
  line_total: Generated<Numeric>;
  product_id: string;
  product_unit_id: string;
  quantity: Numeric;
  quotation_id: string;
  rate: Numeric;
}

export interface Quotations {
  created_at: Generated<Timestamp>;
  created_by: string | null;
  customer_id: string;
  id: Generated<string>;
  quotation_date: Generated<Timestamp>;
  quotation_number: string;
  remarks: string | null;
  status: Generated<string>;
  total_amount: Generated<Numeric>;
  updated_at: Generated<Timestamp>;
  valid_until: Timestamp | null;
}

export interface Racks {
  code: string;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  is_active: Generated<boolean>;
  name: string;
  updated_at: Generated<Timestamp>;
  warehouse_id: string;
}

export interface RefreshTokens {
  created_at: Generated<Timestamp>;
  expires_at: Timestamp;
  id: Generated<string>;
  revoked_at: Timestamp | null;
  token_hash: string;
  user_id: string;
}

export interface ReorderSuggestions {
  avg_daily_demand: Generated<Numeric>;
  calculation_window_days: number;
  current_stock: Generated<Numeric>;
  generated_at: Generated<Timestamp>;
  id: Generated<string>;
  product_id: string;
  recommended_quantity: Generated<Numeric>;
  status: Generated<string>;
  warehouse_id: string;
}

export interface ReservedStock {
  batch_id: string | null;
  expires_at: Timestamp;
  id: Generated<string>;
  product_id: string;
  quantity: Numeric;
  reference_id: string;
  reference_type: string;
  released_at: Timestamp | null;
  reserved_at: Generated<Timestamp>;
  reserved_by: string | null;
  status: Generated<string>;
  warehouse_id: string;
}

export interface RolePermissions {
  permission_id: string;
  role_id: string;
}

export interface Roles {
  created_at: Generated<Timestamp>;
  description: string | null;
  id: Generated<string>;
  is_system_role: Generated<boolean>;
  name: string;
  updated_at: Generated<Timestamp>;
}

export interface SalesDailyAggregates {
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  product_id: string;
  quantity_sold: Generated<Numeric>;
  sale_date: Timestamp;
  sales_amount: Generated<Numeric>;
  warehouse_id: string;
}

export interface SalesInvoiceLines {
  batch_id: string | null;
  discount_percent: Generated<Numeric>;
  gst_id: string | null;
  id: Generated<string>;
  invoice_id: string;
  line_total: Generated<Numeric>;
  product_id: string;
  product_unit_id: string;
  quantity: Numeric;
  rate: Numeric;
  tax_amount: Generated<Numeric>;
}

export interface SalesInvoices {
  approved_at: Timestamp | null;
  approved_by: string | null;
  created_at: Generated<Timestamp>;
  created_by: string | null;
  customer_id: string;
  dc_id: string | null;
  discount_amount: Generated<Numeric>;
  due_date: Timestamp | null;
  financial_year_id: string;
  id: Generated<string>;
  invoice_date: Generated<Timestamp>;
  invoice_number: string;
  paid_amount: Generated<Numeric>;
  so_id: string | null;
  status: Generated<string>;
  subtotal: Generated<Numeric>;
  tax_amount: Generated<Numeric>;
  total_amount: Generated<Numeric>;
  updated_at: Generated<Timestamp>;
}

export interface SalesOrderLines {
  delivered_quantity: Generated<Numeric>;
  discount_percent: Generated<Numeric>;
  gst_id: string | null;
  id: Generated<string>;
  line_total: Generated<Numeric>;
  product_id: string;
  product_unit_id: string;
  quantity: Numeric;
  rate: Numeric;
  so_id: string;
}

export interface SalesOrders {
  approved_at: Timestamp | null;
  approved_by: string | null;
  created_at: Generated<Timestamp>;
  created_by: string | null;
  customer_id: string;
  expected_delivery_date: Timestamp | null;
  financial_year_id: string;
  id: Generated<string>;
  quotation_id: string | null;
  remarks: string | null;
  so_date: Generated<Timestamp>;
  so_number: string;
  status: Generated<string>;
  total_amount: Generated<Numeric>;
  updated_at: Generated<Timestamp>;
  warehouse_id: string;
}

export interface SalesReturnLines {
  batch_id: string | null;
  id: Generated<string>;
  line_total: Generated<Numeric>;
  product_id: string;
  quantity: Numeric;
  rate: Numeric;
  return_id: string;
}

export interface SalesReturns {
  approved_at: Timestamp | null;
  approved_by: string | null;
  created_at: Generated<Timestamp>;
  created_by: string | null;
  customer_id: string;
  id: Generated<string>;
  reason: string | null;
  return_date: Generated<Timestamp>;
  return_number: string;
  sales_invoice_id: string | null;
  status: Generated<string>;
  total_amount: Generated<Numeric>;
  updated_at: Generated<Timestamp>;
  warehouse_id: string;
}

export interface StockAdjustmentLines {
  adjusted_quantity: Numeric;
  adjustment_id: string;
  batch_id: string | null;
  id: Generated<string>;
  location_id: string | null;
  product_id: string;
  rack_id: string | null;
  remarks: string | null;
  system_quantity: Numeric;
}

export interface StockAdjustments {
  adjustment_date: Generated<Timestamp>;
  adjustment_number: string;
  approved_at: Timestamp | null;
  approved_by: string | null;
  created_at: Generated<Timestamp>;
  created_by: string | null;
  id: Generated<string>;
  reason: string | null;
  status: Generated<string>;
  updated_at: Generated<Timestamp>;
  warehouse_id: string;
}

export interface StockBalances {
  average_cost: Generated<Numeric>;
  batch_id: string | null;
  blocked_quantity: Generated<Numeric>;
  id: Generated<string>;
  location_id: string | null;
  product_id: string;
  quantity: Generated<Numeric>;
  rack_id: string | null;
  reserved_quantity: Generated<Numeric>;
  updated_at: Generated<Timestamp>;
  warehouse_id: string;
}

export interface StockLedger {
  batch_id: string | null;
  created_at: Generated<Timestamp>;
  created_by: string | null;
  id: Generated<string>;
  location_id: string | null;
  movement_type: string;
  product_id: string;
  qty_in: Generated<Numeric>;
  qty_out: Generated<Numeric>;
  rack_id: string | null;
  reference_id: string;
  reference_line_id: string | null;
  reference_type: string;
  remarks: string | null;
  unit_cost: Generated<Numeric>;
  warehouse_id: string;
}

export interface StockReturnLines {
  batch_id: string | null;
  id: Generated<string>;
  location_id: string | null;
  product_id: string;
  quantity: Numeric;
  rack_id: string | null;
  remarks: string | null;
  return_id: string;
}

export interface StockReturns {
  approved_at: Timestamp | null;
  approved_by: string | null;
  created_at: Generated<Timestamp>;
  created_by: string | null;
  id: Generated<string>;
  reason: string | null;
  return_date: Generated<Timestamp>;
  return_number: string;
  status: Generated<string>;
  updated_at: Generated<Timestamp>;
  warehouse_id: string;
}

export interface StockTransferLines {
  batch_id: string | null;
  from_location_id: string | null;
  from_rack_id: string | null;
  id: Generated<string>;
  product_id: string;
  quantity: Numeric;
  to_location_id: string | null;
  to_rack_id: string | null;
  transfer_id: string;
}

export interface StockTransfers {
  approved_at: Timestamp | null;
  approved_by: string | null;
  created_at: Generated<Timestamp>;
  created_by: string | null;
  from_warehouse_id: string;
  id: Generated<string>;
  remarks: string | null;
  status: Generated<string>;
  to_warehouse_id: string;
  transfer_date: Generated<Timestamp>;
  transfer_number: string;
  updated_at: Generated<Timestamp>;
}

export interface SubCategories {
  category_id: string;
  code: string;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  is_active: Generated<boolean>;
  name: string;
  updated_at: Generated<Timestamp>;
}

export interface SupplierPaymentAllocations {
  allocated_amount: Numeric;
  id: Generated<string>;
  payment_id: string;
  purchase_invoice_id: string;
}

export interface SupplierPayments {
  amount: Numeric;
  created_at: Generated<Timestamp>;
  created_by: string | null;
  id: Generated<string>;
  payment_date: Generated<Timestamp>;
  payment_mode: string;
  payment_number: string;
  reference_number: string | null;
  remarks: string | null;
  supplier_id: string;
}

export interface Suppliers {
  address_line1: string | null;
  address_line2: string | null;
  blocked_reason: string | null;
  city: string | null;
  code: string;
  contact_person: string | null;
  country: string | null;
  created_at: Generated<Timestamp>;
  credit_period_days: Generated<number>;
  email: string | null;
  gstin: string | null;
  id: Generated<string>;
  is_active: Generated<boolean>;
  is_blocked: Generated<boolean>;
  name: string;
  opening_balance: Generated<Numeric>;
  pan: string | null;
  phone: string | null;
  pincode: string | null;
  state: string | null;
  updated_at: Generated<Timestamp>;
}

export interface Taxes {
  id: Generated<string>;
  is_active: Generated<boolean>;
  name: string;
  rate: Numeric;
  tax_type: string;
}

export interface Transporters {
  code: string;
  contact_person: string | null;
  created_at: Generated<Timestamp>;
  gst_number: string | null;
  id: Generated<string>;
  is_active: Generated<boolean>;
  name: string;
  phone: string | null;
  updated_at: Generated<Timestamp>;
  vehicle_number: string | null;
}

export interface UnitConversions {
  conversion_factor: Numeric;
  created_at: Generated<Timestamp>;
  from_unit_id: string;
  id: Generated<string>;
  to_unit_id: string;
}

export interface Units {
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  is_active: Generated<boolean>;
  name: string;
  short_code: string;
  updated_at: Generated<Timestamp>;
}

export interface UserRoles {
  role_id: string;
  user_id: string;
}

export interface Users {
  avatar_url: string | null;
  created_at: Generated<Timestamp>;
  email: string;
  id: Generated<string>;
  is_active: Generated<boolean>;
  last_login_at: Timestamp | null;
  must_change_password: Generated<boolean>;
  name: string;
  password_hash: string;
  phone: string | null;
  updated_at: Generated<Timestamp>;
}

export interface VCurrentStock {
  available_quantity: Numeric | null;
  average_cost: Numeric | null;
  batch_number: string | null;
  blocked_quantity: Numeric | null;
  expiry_date: Timestamp | null;
  location_name: string | null;
  product_id: string | null;
  product_name: string | null;
  quantity: Numeric | null;
  rack_name: string | null;
  reserved_quantity: Numeric | null;
  sku: string | null;
  stock_balance_id: string | null;
  stock_value: Numeric | null;
  warehouse_id: string | null;
  warehouse_name: string | null;
}

export interface VDeadStock {
  last_sale_date: Timestamp | null;
  product_id: string | null;
  product_name: string | null;
  sku: string | null;
  stock_value: Numeric | null;
  total_quantity: Numeric | null;
}

export interface VLowStockItems {
  minimum_stock: Numeric | null;
  product_id: string | null;
  product_name: string | null;
  reorder_level: Numeric | null;
  sku: string | null;
  total_available: Numeric | null;
  total_quantity: Numeric | null;
}

export interface VOutstandingPayables {
  days_overdue: number | null;
  due_date: Timestamp | null;
  invoice_date: Timestamp | null;
  invoice_number: string | null;
  outstanding_amount: Numeric | null;
  paid_amount: Numeric | null;
  purchase_invoice_id: string | null;
  supplier_id: string | null;
  supplier_name: string | null;
  total_amount: Numeric | null;
}

export interface VOutstandingReceivables {
  customer_id: string | null;
  customer_name: string | null;
  days_overdue: number | null;
  due_date: Timestamp | null;
  invoice_date: Timestamp | null;
  invoice_number: string | null;
  outstanding_amount: Numeric | null;
  paid_amount: Numeric | null;
  sales_invoice_id: string | null;
  total_amount: Numeric | null;
}

export interface VWarehouseStockValue {
  total_quantity: Numeric | null;
  total_stock_value: Numeric | null;
  warehouse_id: string | null;
  warehouse_name: string | null;
}

export interface Warehouses {
  address_line1: string | null;
  branch_id: string;
  city: string | null;
  code: string;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  is_active: Generated<boolean>;
  manager_id: string | null;
  name: string;
  pincode: string | null;
  state: string | null;
  updated_at: Generated<Timestamp>;
}

export interface DB {
  activity_history: ActivityHistory;
  approval_workflows: ApprovalWorkflows;
  audit_logs: AuditLogs;
  blocked_stock_entries: BlockedStockEntries;
  branches: Branches;
  brands: Brands;
  categories: Categories;
  customer_payment_allocations: CustomerPaymentAllocations;
  customer_payments: CustomerPayments;
  customers: Customers;
  damaged_stock: DamagedStock;
  damaged_stock_lines: DamagedStockLines;
  delivery_challan_lines: DeliveryChallanLines;
  delivery_challans: DeliveryChallans;
  document_number_sequences: DocumentNumberSequences;
  employees: Employees;
  financial_years: FinancialYears;
  goods_received_notes: GoodsReceivedNotes;
  grn_lines: GrnLines;
  gst_rates: GstRates;
  hsn_codes: HsnCodes;
  locations: Locations;
  notifications: Notifications;
  otp_codes: OtpCodes;
  permissions: Permissions;
  physical_verification_lines: PhysicalVerificationLines;
  physical_verifications: PhysicalVerifications;
  product_barcodes: ProductBarcodes;
  product_batches: ProductBatches;
  product_images: ProductImages;
  product_price_history: ProductPriceHistory;
  product_units: ProductUnits;
  products: Products;
  purchase_invoice_lines: PurchaseInvoiceLines;
  purchase_invoices: PurchaseInvoices;
  purchase_order_lines: PurchaseOrderLines;
  purchase_orders: PurchaseOrders;
  purchase_return_lines: PurchaseReturnLines;
  purchase_returns: PurchaseReturns;
  quotation_lines: QuotationLines;
  quotations: Quotations;
  racks: Racks;
  refresh_tokens: RefreshTokens;
  reorder_suggestions: ReorderSuggestions;
  reserved_stock: ReservedStock;
  role_permissions: RolePermissions;
  roles: Roles;
  sales_daily_aggregates: SalesDailyAggregates;
  sales_invoice_lines: SalesInvoiceLines;
  sales_invoices: SalesInvoices;
  sales_order_lines: SalesOrderLines;
  sales_orders: SalesOrders;
  sales_return_lines: SalesReturnLines;
  sales_returns: SalesReturns;
  stock_adjustment_lines: StockAdjustmentLines;
  stock_adjustments: StockAdjustments;
  stock_balances: StockBalances;
  stock_ledger: StockLedger;
  stock_return_lines: StockReturnLines;
  stock_returns: StockReturns;
  stock_transfer_lines: StockTransferLines;
  stock_transfers: StockTransfers;
  sub_categories: SubCategories;
  supplier_payment_allocations: SupplierPaymentAllocations;
  supplier_payments: SupplierPayments;
  suppliers: Suppliers;
  taxes: Taxes;
  transporters: Transporters;
  unit_conversions: UnitConversions;
  units: Units;
  user_roles: UserRoles;
  users: Users;
  v_current_stock: VCurrentStock;
  v_dead_stock: VDeadStock;
  v_low_stock_items: VLowStockItems;
  v_outstanding_payables: VOutstandingPayables;
  v_outstanding_receivables: VOutstandingReceivables;
  v_warehouse_stock_value: VWarehouseStockValue;
  warehouses: Warehouses;
}
