-- =====================================================================================
-- TENANT TEMPLATE: Purchase cycle
-- Purchase Order -> Goods Received Note -> Purchase Invoice -> Supplier Payment
-- (+ Purchase Return). Every header carries a sequential, financial-year-scoped document
-- number generated by tenant_template.fn_next_document_number() (see functions/ folder).
-- =====================================================================================
SET search_path TO tenant_template, public;

CREATE TABLE tenant_template.purchase_orders (
  id                   uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  po_number            varchar(30) NOT NULL UNIQUE,
  po_date              date NOT NULL DEFAULT current_date,
  supplier_id          uuid NOT NULL REFERENCES tenant_template.suppliers(id) ON DELETE RESTRICT,
  warehouse_id         uuid NOT NULL REFERENCES tenant_template.warehouses(id) ON DELETE RESTRICT,
  financial_year_id    uuid NOT NULL REFERENCES tenant_template.financial_years(id) ON DELETE RESTRICT,
  expected_delivery_date date,
  status               varchar(25) NOT NULL DEFAULT 'draft' CHECK (status IN
                         ('draft','pending_approval','approved','partially_received','completed','cancelled')),
  remarks              text,
  total_amount         numeric(18,2) NOT NULL DEFAULT 0,
  created_by           uuid REFERENCES tenant_template.users(id) ON DELETE SET NULL,
  approved_by          uuid REFERENCES tenant_template.users(id) ON DELETE SET NULL,
  approved_at          timestamptz,
  created_at           timestamptz NOT NULL DEFAULT now(),
  updated_at           timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX idx_po_supplier ON tenant_template.purchase_orders(supplier_id);
CREATE INDEX idx_po_status ON tenant_template.purchase_orders(status);
CREATE TRIGGER trg_po_updated_at BEFORE UPDATE ON tenant_template.purchase_orders
  FOR EACH ROW EXECUTE FUNCTION public.fn_set_updated_at();

CREATE TABLE tenant_template.purchase_order_lines (
  id                 uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  po_id              uuid NOT NULL REFERENCES tenant_template.purchase_orders(id) ON DELETE CASCADE,
  product_id         uuid NOT NULL REFERENCES tenant_template.products(id) ON DELETE RESTRICT,
  product_unit_id    uuid NOT NULL REFERENCES tenant_template.product_units(id) ON DELETE RESTRICT,
  quantity           numeric(18,3) NOT NULL CHECK (quantity > 0),
  received_quantity  numeric(18,3) NOT NULL DEFAULT 0 CHECK (received_quantity >= 0),
  rate               numeric(18,2) NOT NULL CHECK (rate >= 0),
  discount_percent   numeric(5,2) NOT NULL DEFAULT 0,
  gst_id             uuid REFERENCES tenant_template.gst_rates(id) ON DELETE RESTRICT,
  line_total         numeric(18,2) NOT NULL DEFAULT 0
);
CREATE INDEX idx_po_lines_po ON tenant_template.purchase_order_lines(po_id);

CREATE TABLE tenant_template.goods_received_notes (
  id              uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  grn_number      varchar(30) NOT NULL UNIQUE,
  grn_date        date NOT NULL DEFAULT current_date,
  po_id           uuid REFERENCES tenant_template.purchase_orders(id) ON DELETE RESTRICT,
  supplier_id     uuid NOT NULL REFERENCES tenant_template.suppliers(id) ON DELETE RESTRICT,
  warehouse_id    uuid NOT NULL REFERENCES tenant_template.warehouses(id) ON DELETE RESTRICT,
  transporter_id  uuid REFERENCES tenant_template.transporters(id) ON DELETE SET NULL,
  status          varchar(20) NOT NULL DEFAULT 'draft' CHECK (status IN ('draft','completed','cancelled')),
  remarks         text,
  created_by      uuid REFERENCES tenant_template.users(id) ON DELETE SET NULL,
  created_at      timestamptz NOT NULL DEFAULT now(),
  updated_at      timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX idx_grn_po ON tenant_template.goods_received_notes(po_id);
CREATE INDEX idx_grn_supplier ON tenant_template.goods_received_notes(supplier_id);
CREATE TRIGGER trg_grn_updated_at BEFORE UPDATE ON tenant_template.goods_received_notes
  FOR EACH ROW EXECUTE FUNCTION public.fn_set_updated_at();

CREATE TABLE tenant_template.grn_lines (
  id              uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  grn_id          uuid NOT NULL REFERENCES tenant_template.goods_received_notes(id) ON DELETE CASCADE,
  po_line_id      uuid REFERENCES tenant_template.purchase_order_lines(id) ON DELETE RESTRICT,
  product_id      uuid NOT NULL REFERENCES tenant_template.products(id) ON DELETE RESTRICT,
  product_unit_id uuid NOT NULL REFERENCES tenant_template.product_units(id) ON DELETE RESTRICT,
  batch_id        uuid REFERENCES tenant_template.product_batches(id) ON DELETE RESTRICT,
  quantity        numeric(18,3) NOT NULL CHECK (quantity > 0),
  rate            numeric(18,2) NOT NULL CHECK (rate >= 0),
  remarks         text
);
CREATE INDEX idx_grn_lines_grn ON tenant_template.grn_lines(grn_id);

CREATE TABLE tenant_template.purchase_invoices (
  id                     uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  invoice_number         varchar(30) NOT NULL UNIQUE,
  invoice_date           date NOT NULL DEFAULT current_date,
  supplier_invoice_number varchar(60),
  grn_id                 uuid REFERENCES tenant_template.goods_received_notes(id) ON DELETE RESTRICT,
  po_id                  uuid REFERENCES tenant_template.purchase_orders(id) ON DELETE RESTRICT,
  supplier_id            uuid NOT NULL REFERENCES tenant_template.suppliers(id) ON DELETE RESTRICT,
  financial_year_id      uuid NOT NULL REFERENCES tenant_template.financial_years(id) ON DELETE RESTRICT,
  due_date               date,
  status                 varchar(20) NOT NULL DEFAULT 'draft' CHECK (status IN
                          ('draft','approved','partially_paid','paid','cancelled')),
  subtotal               numeric(18,2) NOT NULL DEFAULT 0,
  tax_amount             numeric(18,2) NOT NULL DEFAULT 0,
  discount_amount        numeric(18,2) NOT NULL DEFAULT 0,
  total_amount           numeric(18,2) NOT NULL DEFAULT 0,
  paid_amount            numeric(18,2) NOT NULL DEFAULT 0,
  created_by             uuid REFERENCES tenant_template.users(id) ON DELETE SET NULL,
  approved_by            uuid REFERENCES tenant_template.users(id) ON DELETE SET NULL,
  approved_at            timestamptz,
  created_at             timestamptz NOT NULL DEFAULT now(),
  updated_at             timestamptz NOT NULL DEFAULT now(),
  CHECK (paid_amount <= total_amount)
);
CREATE INDEX idx_purchase_invoices_supplier ON tenant_template.purchase_invoices(supplier_id);
CREATE INDEX idx_purchase_invoices_status ON tenant_template.purchase_invoices(status);
CREATE TRIGGER trg_purchase_invoices_updated_at BEFORE UPDATE ON tenant_template.purchase_invoices
  FOR EACH ROW EXECUTE FUNCTION public.fn_set_updated_at();

CREATE TABLE tenant_template.purchase_invoice_lines (
  id                uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  invoice_id        uuid NOT NULL REFERENCES tenant_template.purchase_invoices(id) ON DELETE CASCADE,
  product_id        uuid NOT NULL REFERENCES tenant_template.products(id) ON DELETE RESTRICT,
  product_unit_id   uuid NOT NULL REFERENCES tenant_template.product_units(id) ON DELETE RESTRICT,
  batch_id          uuid REFERENCES tenant_template.product_batches(id) ON DELETE RESTRICT,
  quantity          numeric(18,3) NOT NULL CHECK (quantity > 0),
  rate              numeric(18,2) NOT NULL CHECK (rate >= 0),
  discount_percent  numeric(5,2) NOT NULL DEFAULT 0,
  gst_id            uuid REFERENCES tenant_template.gst_rates(id) ON DELETE RESTRICT,
  tax_amount        numeric(18,2) NOT NULL DEFAULT 0,
  line_total        numeric(18,2) NOT NULL DEFAULT 0
);
CREATE INDEX idx_purchase_invoice_lines_invoice ON tenant_template.purchase_invoice_lines(invoice_id);

CREATE TABLE tenant_template.supplier_payments (
  id               uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  payment_number   varchar(30) NOT NULL UNIQUE,
  payment_date     date NOT NULL DEFAULT current_date,
  supplier_id      uuid NOT NULL REFERENCES tenant_template.suppliers(id) ON DELETE RESTRICT,
  amount           numeric(18,2) NOT NULL CHECK (amount > 0),
  payment_mode     varchar(20) NOT NULL CHECK (payment_mode IN ('cash','bank_transfer','cheque','upi','card','other')),
  reference_number varchar(60),
  remarks          text,
  created_by       uuid REFERENCES tenant_template.users(id) ON DELETE SET NULL,
  created_at       timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX idx_supplier_payments_supplier ON tenant_template.supplier_payments(supplier_id);

-- Allows one payment to be split across multiple purchase invoices (and vice versa).
CREATE TABLE tenant_template.supplier_payment_allocations (
  id                   uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  payment_id           uuid NOT NULL REFERENCES tenant_template.supplier_payments(id) ON DELETE CASCADE,
  purchase_invoice_id  uuid NOT NULL REFERENCES tenant_template.purchase_invoices(id) ON DELETE RESTRICT,
  allocated_amount     numeric(18,2) NOT NULL CHECK (allocated_amount > 0)
);
CREATE INDEX idx_supplier_payment_allocations_payment ON tenant_template.supplier_payment_allocations(payment_id);
CREATE INDEX idx_supplier_payment_allocations_invoice ON tenant_template.supplier_payment_allocations(purchase_invoice_id);

CREATE TABLE tenant_template.purchase_returns (
  id                  uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  return_number       varchar(30) NOT NULL UNIQUE,
  return_date         date NOT NULL DEFAULT current_date,
  supplier_id         uuid NOT NULL REFERENCES tenant_template.suppliers(id) ON DELETE RESTRICT,
  purchase_invoice_id uuid REFERENCES tenant_template.purchase_invoices(id) ON DELETE RESTRICT,
  warehouse_id        uuid NOT NULL REFERENCES tenant_template.warehouses(id) ON DELETE RESTRICT,
  reason              text,
  status              varchar(20) NOT NULL DEFAULT 'draft' CHECK (status IN ('draft','approved','cancelled')),
  total_amount        numeric(18,2) NOT NULL DEFAULT 0,
  created_by          uuid REFERENCES tenant_template.users(id) ON DELETE SET NULL,
  approved_by         uuid REFERENCES tenant_template.users(id) ON DELETE SET NULL,
  approved_at         timestamptz,
  created_at          timestamptz NOT NULL DEFAULT now(),
  updated_at          timestamptz NOT NULL DEFAULT now()
);
CREATE TRIGGER trg_purchase_returns_updated_at BEFORE UPDATE ON tenant_template.purchase_returns
  FOR EACH ROW EXECUTE FUNCTION public.fn_set_updated_at();

CREATE TABLE tenant_template.purchase_return_lines (
  id          uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  return_id   uuid NOT NULL REFERENCES tenant_template.purchase_returns(id) ON DELETE CASCADE,
  product_id  uuid NOT NULL REFERENCES tenant_template.products(id) ON DELETE RESTRICT,
  batch_id    uuid REFERENCES tenant_template.product_batches(id) ON DELETE RESTRICT,
  quantity    numeric(18,3) NOT NULL CHECK (quantity > 0),
  rate        numeric(18,2) NOT NULL CHECK (rate >= 0),
  line_total  numeric(18,2) NOT NULL DEFAULT 0
);
CREATE INDEX idx_purchase_return_lines_return ON tenant_template.purchase_return_lines(return_id);
